[package]
edition = "2021"
name    = "zero2prod"
version = "0.1.0"

[lib]
path = "src/lib.rs"

[[bin]]
name = "zero2prod"
path = "src/main.rs"

[dependencies]
axum  = { git = "https://github.com/tokio-rs/axum" }
hyper = { version = "1.0.0-rc.3", features = ["full"] }
serde = { version = "1.0.164", features = ["derive"] }
surrealdb = "1.0.0-beta.9"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }

[dev-dependencies]
reqwest = "0.11"
